apiVersion: apps/v1
kind: Deployment
metadata:
  name: welcome-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: welcome-app
  template:
    metadata:
      labels:
        app: welcome-app
    spec:
      containers:
        - name: welcome-app
          image: welcomekoost-app:latest
          ports:
            - containerPort: 8080
